# n = str(input("digite seu nome completo: "))
# print("MAIÚSCULO: ",n.upper())
# print("minúsculo: ",n.lower())
# len(n.strip()))
# n = (len(n.strip()))-1)
# print(n)
n= str(input("nome completo please: ")).strip()
print("seu nome em MAIÚSCULO é {} ".format(n.upper()))
print("seu nome em minúsculo é {} ".format(n.lower()))
print("seu nome tem {} letras".format(len(n) - n.count(" ")))
# print(" seu primeiro nome tem {} letras ".format(n.find(" ")))
segmentos = n.split()
print(" seu primeiro é {} e seu nome tem {} letras". format(segmentos[0],len(segmentos[0])))